### PR TITLE
style(branding): ClassicPress logos

### LINKED ISSUE #34: Branding: Replace logo files
One thing I realized just now, we never changed the file names of logo files. They still say `wordpress-logo.svg` in ClassicPress. I don't know what copyright/trademark implications this may or may not have, but we should do it correctly and change file names this time.

`wordpress-logo.svg|png`
- [x] src/wp-admin/css/install-rtl.css
- [x] src/wp-admin/css/install.css
- [x] src/wp-admin/css/login-rtl.css
- [x] src/wp-admin/css/login.css
- [x] src/readme.html

`wordpress-logo-white.svg`
- [x] src/wp-admin/css/about.css
- [x] src/wp-admin/css/about-rtl.css

`w-logo-white.png`
- [x] src/wp-admin/css/about.css
- [x] src/wp-admin/css/about-rtl.css

`w-logo-blue.png`
- [x] src/wp-admin/css/install-rtl.css
- [x] src/wp-admin/css/install.css
- [x] src/wp-admin/css/login-rtl.css
- [x] src/wp-admin/css/login.css
- [x] src/wp-includes/embed.php

`Misc. images`
- [x] 2 logo files in `\src\wp-includes\images`

### PR DESCRIPTION
**Pull request by viktorix**
Replaced WordPress logo files with ClassicPress and changed file names across relevant files. Closes #34 

Verified with `grep` command several times that all logo file names have been replaced/changed.

### CODE REVIEW

**Review by xxsimoxx — CHANGES_REQUESTED** [review]
I'm getting this on login page:
`GET https://v2:8890/wp-admin/images/wordpress-logo.svg?ver=20131107 404 (Not Found)`

**Comment by viktorix** [comment]
@xxsimoxx wp-login.php does not have a logo image, only login.css, which was updated. Could you please either do a hard refresh or try incognito mode to see if it's a cached login.css? 

`wordpress-logo.svg` was replaced with `classicpress-logo.svg` in login.css.

**Comment by xxsimoxx** [comment]
@viktorix I see an error in the console about missing files.
I checked out the PR and when you reload switching to main shows the WP logo, switching to the PR branch there is no logo and an error.

**Comment by viktorix** [comment]
@xxsimoxx thanks, let me do more digging.

**Comment by viktorix** [comment]
@xxsimoxx It was the minified files. I did not change them because they are generated during build. Which also means we need to delete minified files from `src`. Please, set `define( 'SCRIPT_DEBUG', true );` while testing `src` files. This will switch everything over to original CSS/JS files.

**Pull request closed without merging**
